version: '3'
services:
  ## PostgreSQL Docker Compose Config
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: invoice_master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: unless-stopped