spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoice-master
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        format_sql: true
  sql:
    init:
      mode: never

